import { existsSync } from "node:fs";
import { resolve } from "node:path";
import nodemailer from "nodemailer";
import { BRAND } from "@/lib/brand";

export const smtpConfigured = Boolean(
  process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASSWORD,
);

let transporter: nodemailer.Transporter | null = null;

function getTransporter() {
  if (!smtpConfigured) return null;
  if (!transporter) {
    const port = Number(process.env.SMTP_PORT ?? 587);
    transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port,
      secure: port === 465,
      auth: { user: process.env.SMTP_USER!, pass: process.env.SMTP_PASSWORD! },
    });
  }
  return transporter;
}

export type SendResult = { delivered: boolean; error?: string };

/**
 * Never throws. A mail provider failing is an operational problem, not a
 * request-shaped one — the caller decides what to tell the user, and the code
 * is always written to the console so an operator is never locked out.
 */
export async function sendOtpEmail(to: string, code: string, name?: string): Promise<SendResult> {
  const logCode = () =>
    console.info(`\n  [IEV] Login code for ${to}: ${code}  (valid 10 minutes)\n`);

  const tx = getTransporter();
  if (!tx) {
    // No SMTP configured — the console is the delivery channel.
    logCode();
    return { delivered: false };
  }

  const from = process.env.SMTP_FROM?.trim();
  if (!from) {
    logCode();
    return {
      delivered: false,
      error:
        "SMTP is configured but SMTP_FROM is not set. Most providers reject mail from an unverified sender. Set SMTP_FROM to an address on a domain verified with your mail provider.",
    };
  }

  try {
    await tx.sendMail({ from, to, ...buildOtpMessage(code, name) });
    return { delivered: true };
  } catch (err) {
    console.error("[mailer] Could not send sign-in code:", err);
    logCode();
    return { delivered: false, error: describeSmtpError(err, from) };
  }
}

/** Turns an SMTP failure into something an administrator can act on. */
function describeSmtpError(err: unknown, from: string): string {
  const code = (err as { responseCode?: number })?.responseCode;
  const raw = err instanceof Error ? err.message : String(err);

  if (code === 553 || code === 550 || /not allowed to relay|sender.*not/i.test(raw)) {
    return `The mail provider refused "${from}" as a sender. The From address must be on a domain verified with your provider — update SMTP_FROM.`;
  }
  if (code === 535 || /auth|credential/i.test(raw)) {
    return "The mail provider rejected the SMTP credentials. Check SMTP_USER and SMTP_PASSWORD.";
  }
  if (/ENOTFOUND|ECONNREFUSED|ETIMEDOUT/i.test(raw)) {
    return "Could not reach the mail server. Check SMTP_HOST, SMTP_PORT and the server's network access.";
  }
  return `The mail provider rejected the message: ${raw}`;
}

const LOGO_CID = "xlri-logo";

/**
 * The email logo is embedded in the message rather than linked.
 *
 * A linked image needs a public URL the portal may not have, and most clients
 * block remote images by default — so the logo would be a grey box on first
 * open, which is exactly when trust matters. Attaching it inline sidesteps
 * both. Generated by `npm run email:logo`; if it is missing the email simply
 * falls back to the text header rather than showing a broken image.
 */
function logoAttachment() {
  const path = resolve(process.cwd(), "public/xlri-logo-email.png");
  if (!existsSync(path)) return null;
  return {
    filename: "xlri-logo.png",
    path,
    cid: LOGO_CID,
    contentDisposition: "inline" as const,
  };
}

/** Builds the full message body. Exported so it can be inspected in tests. */
export function buildOtpMessage(code: string, name?: string) {
  const logo = logoAttachment();
  return {
    subject: `${code} is your ${BRAND.unitShort} Portal sign-in code`,
    text: [
      `${BRAND.institutionFull}, ${BRAND.campus}`,
      `${BRAND.unit}`,
      ``,
      `Your sign-in code is ${code}`,
      `It expires in 10 minutes and can be used once.`,
      ``,
      `If you did not request this code, you can ignore this email.`,
    ].join("\n"),
    html: otpEmailHtml(code, name, Boolean(logo)),
    ...(logo ? { attachments: [logo] } : {}),
  };
}

function otpEmailHtml(code: string, name?: string, withLogo = false) {
  // Table layout and inline styles throughout — Outlook renders with Word,
  // which ignores flexbox, grid and most external CSS.
  const masthead = withLogo
    ? `<img src="cid:${LOGO_CID}" width="180" alt="${escapeHtml(BRAND.institutionFull)}"
            style="display:block;border:0;outline:none;text-decoration:none;width:180px;max-width:180px;height:auto" />`
    : `<span style="font-size:20px;font-weight:700;color:#1c3f94;letter-spacing:-0.02em">XLR<span style="color:#6fa32c">i</span></span>
       <div style="margin-top:2px;font-size:11px;color:#939598">${escapeHtml(BRAND.institutionFull)}</div>`;

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="color-scheme" content="light only" />
<title>Sign-in code</title></head>
<body style="margin:0;padding:32px 16px;background:#f1f5f9;font-family:ui-sans-serif,system-ui,'Segoe UI',Arial,sans-serif;color:#101828">
  <!-- preview text shown in the inbox list, before the message is opened -->
  <div style="display:none;max-height:0;overflow:hidden;opacity:0">${code} is your sign-in code. It expires in 10 minutes.</div>

  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
    <tr><td align="center">
      <table role="presentation" width="500" cellpadding="0" cellspacing="0" border="0"
             style="width:500px;max-width:100%;background:#ffffff;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden">

        <!-- Masthead: the logo sits on white so the crest keeps its colours -->
        <tr><td align="left" style="padding:24px 28px 20px">${masthead}</td></tr>

        <!-- the green rule from the identity -->
        <tr><td style="height:3px;background:#8dc63f;font-size:0;line-height:0">&nbsp;</td></tr>

        <tr><td style="background:#1c3f94;padding:13px 28px;color:#ffffff;font-size:13.5px;font-weight:600;letter-spacing:.02em">
          ${escapeHtml(BRAND.unitShort)} ${escapeHtml(BRAND.product)}
          <span style="color:#b9cbee;font-weight:400"> &middot; ${escapeHtml(BRAND.campus)}</span>
        </td></tr>

        <tr><td style="padding:28px">
          <p style="margin:0 0 6px;font-size:15px;color:#101828">Hello${name ? ` ${escapeHtml(name)}` : ""},</p>
          <p style="margin:0 0 20px;font-size:14px;line-height:22px;color:#5a6577">
            Use the code below to sign in to the ${escapeHtml(BRAND.unit)} portal.
          </p>

          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr><td align="center" style="padding:20px 12px;background:#f6f8fc;border:1px dashed #c0d2f1;border-radius:10px">
              <div style="font-size:34px;line-height:1;font-weight:700;letter-spacing:.30em;color:#1c3f94;font-family:ui-monospace,'Cascadia Code','Courier New',monospace">${code}</div>
              <div style="margin-top:10px;font-size:12px;color:#5a6577">Expires in 10 minutes &middot; can be used once</div>
            </td></tr>
          </table>

          <p style="margin:22px 0 0;font-size:12px;line-height:18px;color:#5a6577">
            If you did not request this code, you can safely ignore this email &mdash;
            no one can sign in without it.
          </p>
        </td></tr>

        <tr><td style="padding:16px 28px 20px;border-top:1px solid #e2e8f0;background:#fafbfc">
          <div style="font-size:11px;line-height:17px;color:#939598">
            ${escapeHtml(BRAND.institutionFull)} &middot; ${escapeHtml(BRAND.campus)}<br />
            <span style="color:#6fa32c;font-style:italic">${escapeHtml(BRAND.tagline)}</span>
          </div>
        </td></tr>
      </table>

      <div style="margin-top:14px;font-size:11px;color:#8a93a3">
        This is an automated message from the ${escapeHtml(BRAND.unitShort)} portal. Please do not reply.
      </div>
    </td></tr>
  </table>
</body></html>`;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (c) => {
    const map: Record<string, string> = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;",
    };
    return map[c];
  });
}
